name: PerMutation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - biopython
  - numpy
  - scipy
  - pysam
  - trimmomatic
  - fastx_toolkit
  - bowtie2
  - samtools